spring:
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

